repos:
  # Hooks para Black (formateador de código)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Formateo de código con Black
        language_version: python3.10

  # Hooks para isort (ordenar importaciones)
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: Ordenar importaciones con isort
        language_version: python3.10

  # Hooks para Ruff (linter rápido y eficiente)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        name: Linting rápido con Ruff
        args: [--fix]  # Corrige automáticamente algunos errores si es posible
        language_version: python3.10

  # Hooks para Flake8 (verificación de estilo PEP8)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Verificación de estilo con Flake8
        language_version: python3.10

  # Hooks para pre-commit-hooks (varios hooks útiles)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace  # Elimina espacios en blanco al final de las líneas
        name: Eliminar espacios en blanco
      - id: end-of-file-fixer  # Asegura que los archivos terminan con una línea en blanco
        name: Corregir fin de archivo
      - id: check-merge-conflict  # Verifica si hay conflictos de merge no resueltos
        name: Verificar conflictos de merge

  # Hook para verificar la construcción de la documentación con Sphinx
  - repo: https://github.com/pre-commit/mirrors-sphinx
    rev: v1.0
    hooks:
      - id: sphinx-build
        name: Verificar la documentación de Sphinx
        args: ['-b', 'html', 'docs/', 'docs/_build/html']

  # Hook para limpiar salidas de Jupyter Notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        name: Limpiar salidas de Jupyter Notebooks
